travis:
  secure:
    BINSTAR_TOKEN: NIlXJsRy+cGYLUkmE00BrrNN/NnB3RztGFjXcR7d1kYLK4n0d442s3YZ+TPnlxOA/xJ4VcNPucUyyo6yp3YmVJZ2cemC8JN0mSxiHTRm0cjkksPczJg3q2Lp8mo9p+bto5M/mtiiKlvFPRqqEqpswp+oWyqBS7PHJ838N7lHzlxyKA/ZwBJ56Vu1+q0yUBKWFf1Hmhm210jh3x/wAPKxdljvNC2YxZzfgZdNdXcEeJOJjLxyMhCdPXzg247RfkJSySQSi3oGYo+xFAWbgH7y4IHqjS/PbXbOxzDdW8y35d2YgDBckcJfhM8yFsewTyzgUVrrojXsDnvjgVVQibVCGOEA9bGbKJ14p1VUX+Qk6AHz1oRt6NNdfI6CbMxot/WCnLyZZFvT2IhKdgoSn/04SUmFmVA5BwyGD7TpmCCBTGOSFPiX4rqFpVPtMYUnsEgK+kMTls/00UrRBtdCeSb+f00G2lR3msjQop8okTu6muk7gOszhAknxQHZnERfnqkq/ftOJ8AJ3dZaWkum9V/l3Ao2gAhp+jZxdizbaSm2CPw1JDvRzWCqyOEA84Rht5h1PQ98MpIvVp7+dXY7830rgy8E3W88F/K4M+5GnCTWdI6eglB2Az6GfOS5jJN7k63QdZUJX1TBwRDdVXoLGbR1lCvwqh1sDF/etRYK/Iezyhs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
