travis:
  secure:
    BINSTAR_TOKEN: KETkCrQU0BJUZxRpyL4Y13BOOJsI30UWtyYogytwbnzb6hHgw9KVrLL8q0PIGobcc5KgWyMb7wqlAxt1q/Dk1jxNYUXwKRWswV9PM1flxamaMjuCefiNo0bcedCs3ndyI1xcRbVyGyFpeoVX15/8lmlWH0DN966OXlza2qtIPPYaOsqW8LuFgtZnq5Rx9UvTfR6maNCghTwtzS+OejMKIxiGI2A2ABX0f5mVfV1vYjQ/B/IAFdUaH6eHTzzrikCTEL5HI8hRHjKZOio34D608oip6eQck95Q+JPyD8M4OhRyTQ+o9pQJITt2VPbHbtpEdmKpR4PlWWHsWqqc0YvL8s0/Fyph1w501BhAhwisEQA9E9xQ/PaEQerA46h8qxonP2B8EOlpdw0llbLVgRRxhff1VtfoQsEHwCSsLmopnGACSeETPN0TPgFP472sop5247Xj01CnX9mALOmjXGL1Q0k2bGBC3hfDa3iLJQ3HMFbsZqzpQwa/MVRDSGHZyaQNpB+6bnXTG+gwG3ooXNMIrJxYd9Ottovvp9GPjDUOv0fYswbe1U16NceLmAeV/IEEfkkVaSBjERk7G4tGvZjNXjD0SfQ3DaYXEYAhIvxm+RfkZo03FOZikniyVOjnmDwixiCFRJxYR+mKsHG+llSeTPjgGYcXaI99gGBB4rB3FIM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
